### ISSUE TITLE
make start-tileserver uses old themes

### ISSUE THREAD

**Issue by lincomatic** [klokantech/openmaptiles#3]
The generated mbtiles use schema 3.5, but "make start-tileserver" starts a tile server with incompatible themes, based on an older version of the schema, which doesn't support the new transportation_name shields

**Comment by klokan** [comment]
This ticket has nothing to do with the fork of openmaptiles done by klokantech - where we work on new functionality.

Please post it to TileServer GL repository - if the issue is related to that open-source project. Thanks.
