### ISSUE TITLE
CreateLayer failed during docker-compose run import-natural-earth

### ISSUE THREAD

**Issue by jendrusk** [klokantech/openmaptiles#4]
Following documentation in third step "docker-compose run import-natural-earth" there is an error - tables already exists in database.

root@52820-1-64096c-01:/srv/openmaptiles/openmaptiles# docker-compose run import-natural-earth
WARNING: The MIN_ZOOM variable is not set. Defaulting to a blank string.
WARNING: The MAX_ZOOM variable is not set. Defaulting to a blank string.
WARNING: The BBOX variable is not set. Defaulting to a blank string.
Pulling import-natural-earth (openmaptiles/import-natural-earth:1.3)...
1.3: Pulling from openmaptiles/import-natural-earth
ef0380f84d05: Already exists
50cf91dc1db8: Already exists
d3add4cd115c: Already exists
467830d8a616: Already exists
089b9db7dc57: Already exists
6fba0a36935c: Already exists
81ef0e73c953: Already exists
338a6c4894dc: Already exists
15853f32f67c: Already exists
044c83d92898: Already exists
17301519f133: Already exists
dcca70822752: Already exists
cecf11b8ccf3: Already exists
b870500e2a13: Already exists
a69fef5f3b8f: Already exists
83827630b390: Pull complete
54c22bc64c50: Pull complete
fa5f8325bc7c: Pull complete
Digest: sha256:57b1770220b7aa6300dc6e62f4a15285488ae16526631bec12311e3aab4dcc10
Status: Downloaded newer image for openmaptiles/import-natural-earth:1.3
Importing Natural Earth to PostGIS
ERROR 1: Layer ne_10m_admin_0_boundary_lines_disputed_areas already exists, CreateLayer failed.
Use the layer creation option OVERWRITE=YES to replace it.
ERROR 1: Terminating translation prematurely after failed
translation of layer ne_10m_admin_0_boundary_lines_disputed_areas (use -skipfailures to skip errors)

**Comment by jendrusk** [comment]
Same with next step:

root@52820-1-64096c-01:/srv/openmaptiles/openmaptiles# docker-compose run import-lakelines
WARNING: The MIN_ZOOM variable is not set. Defaulting to a blank string.
WARNING: The MAX_ZOOM variable is not set. Defaulting to a blank string.
WARNING: The BBOX variable is not set. Defaulting to a blank string.
Pulling import-lakelines (openmaptiles/import-lakelines:1.0)...
1.0: Pulling from openmaptiles/import-lakelines
ef0380f84d05: Already exists
50cf91dc1db8: Already exists
d3add4cd115c: Already exists
467830d8a616: Already exists
089b9db7dc57: Already exists
6fba0a36935c: Already exists
81ef0e73c953: Already exists
338a6c4894dc: Already exists
15853f32f67c: Already exists
044c83d92898: Already exists
17301519f133: Already exists
dcca70822752: Already exists
cecf11b8ccf3: Already exists
b870500e2a13: Already exists
a69fef5f3b8f: Already exists
f0db8c63459d: Pull complete
faac69570799: Pull complete
602b7c4a1829: Pull complete
Digest: sha256:0168dd876ce028c6147e91014a15acfb83e45903525c71204098455210e502a5
Status: Downloaded newer image for openmaptiles/import-lakelines:1.0
FAILED: Layer lake_centerline already exists, and -append not specified.
        Consider using -append, or -overwrite.
ERROR 1: Terminating translation prematurely after failed
translation of layer OGRGeoJSON (use -skipfailures to skip errors)

**Comment by ryku123** [comment]
Have you tried setting first `MIN_ZOOM`, `MAX_ZOOM` variables to bound   the range a lil bit and set OVERWRITE=YES parameter to actually override the data that have been already created? 

This looks like You have made an attempt previously and script hits existing data. 

so try to run and share output of: `docker-compose run import-lakelines -OVERWRITE=YES`

**Comment by jendrusk** [comment]
Hi, Thanks for replay. I followed instructions from main .md, before every attempyt I removed all dockers. In second attempt I checked database before processing and looks like this data is already included into docker... If so it's good cause it's shortening all process, but there is not one word about it in instruction.

**Comment by jirik** [comment]
This is just fork. Please create issues in main repo: https://github.com/openmaptiles/openmaptiles
